### ISSUE TITLE
Cracked Stone Bricks Parity

### ISSUE THREAD

**Issue by Sunsprint** [MushirMickeyJoe/Relatively-Improved-Default#53]
The item form of Cracked Stone Bricks & the placed form of Cracked Stone Bricks render different textures. The same is true of the infested version.

**Comment by MushirMickeyJoe** [comment]
All infested blocks have a custom item texture to indicate the block being infested. This prevents people from accidentally building with these blocks.
Is that what you're referring to?

**Comment by Sunsprint** [comment]
I am aware of the infested border indicator, but the actual texture of the block when placed is different from the item's rendered texture in the inventory; in the inventory a default cracked stone bricks texture is showed, whereas when placed the cracked stone bricks look more like broken stones in dirt.

**Comment by MushirMickeyJoe** [comment]
that'a just a random variant.
