### ISSUE TITLE
Armor Variants Not Changing

### ISSUE THREAD

**Issue by TheChromeDino** [MushirMickeyJoe/Relatively-Improved-Default#65]
I have Optifine downloadade and the resource pack is on top but the armor is not changing when I rename them.

**Comment by MushirMickeyJoe** [comment]
OptiFine for 1.20.4 currently doesn't support CIT yet...

it does, by the way. But only CIT created in the world before the world was updated to 1.20.4. The strangest bug.
In case the Fabulously Optimized Modpack is more updated now, you could always check it out to compare it to the latest OptiFine release. Often times they're faster on development than OF.

join my discord for closer coms if you aren't there yet: https://discord.gg/qkvw29ZNSG
I also have a pack-feedback channel. It's just a faster channel for me to respond in than GitHub,
